<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Material;
use Carbon\Carbon;

class MaterialSeeder extends Seeder
{
    /**
     * Jalankan database seeds.
     */
    public function run(): void
    {
        // Sample data sesuai format yang diberikan user
        $materials = [
            [
                'nomor' => 1,
                'company_code' => '5300',
                'company_code_description' => 'UID Jawa Barat',
                'plant' => '5319',
                'plant_description' => 'PLN UP3 Cimahi',
                'storage_location' => '2080',
                'storage_location_description' => 'APJ Cimahi',
                'material_type' => 'ZST1',
                'material_type_description' => 'PLN Stock Materials',
                'material_code' => '000000001060068',
                'material_description' => 'ISOLATOR;PINPOST;PORC;24KV;;12.5kN',
                'material_group' => 'ZM0106',
                'base_unit_of_measure' => 'PCS',
                'valuation_type' => 'NORMAL',
                'unrestricted_use_stock' => 60.000,
                'quality_inspection_stock' => 0.000,
                'blocked_stock' => 0.000,
                'in_transit_stock' => 0.000,
                'project_stock' => 0.000,
                'wbs_element' => '',
                'valuation_class' => '1000',
                'valuation_description' => 'HAR-Isolator',
                'harga_satuan' => 125000,
                'total_harga' => 7500000,
                'currency' => 'IDR',
                'pabrikan' => 'KENTJANA SAKTI INDONESIA',
                'normalisasi' => '',
                'qty' => 60,
                'tanggal_terima' => Carbon::parse('2025-01-15'),
                'keterangan' => 'Proses',
                'status' => Material::STATUS_BAIK,
            ],
            [
                'nomor' => 2,
                'company_code' => '5300',
                'company_code_description' => 'UID Jawa Barat',
                'plant' => '5319',
                'plant_description' => 'PLN UP3 Cimahi',
                'storage_location' => '2080',
                'storage_location_description' => 'APJ Cimahi',
                'material_type' => 'ZST1',
                'material_type_description' => 'PLN Stock Materials',
                'material_code' => '000000001060069',
                'material_description' => 'ISOLATOR;STRAIN KAP PIN;PORC;24KV;;70kN',
                'material_group' => 'ZM0106',
                'base_unit_of_measure' => 'PCS',
                'valuation_type' => 'NORMAL',
                'unrestricted_use_stock' => 40.000,
                'quality_inspection_stock' => 0.000,
                'blocked_stock' => 0.000,
                'in_transit_stock' => 0.000,
                'project_stock' => 0.000,
                'wbs_element' => '',
                'valuation_class' => '1000',
                'valuation_description' => 'HAR-Isolator',
                'harga_satuan' => 175000,
                'total_harga' => 7000000,
                'currency' => 'IDR',
                'pabrikan' => 'KENTJANA SAKTI INDONESIA',
                'normalisasi' => '',
                'qty' => 40,
                'tanggal_terima' => Carbon::parse('2025-01-15'),
                'keterangan' => 'SELESAI',
                'status' => Material::STATUS_RUSAK,
            ],
            [
                'nomor' => 3,
                'company_code' => '5300',
                'company_code_description' => 'UID Jawa Barat',
                'plant' => '5319',
                'plant_description' => 'PLN UP3 Cimahi',
                'storage_location' => '2080',
                'storage_location_description' => 'APJ Cimahi',
                'material_type' => 'ZST1',
                'material_type_description' => 'PLN Stock Materials',
                'material_code' => '000000001060070',
                'material_description' => 'CABLE PWR;NFA2X-T;3X35+1X35;0.6/1kV;OH',
                'material_group' => 'ZM0107',
                'base_unit_of_measure' => 'M',
                'valuation_type' => 'NORMAL',
                'unrestricted_use_stock' => 1.000,
                'quality_inspection_stock' => 0.000,
                'blocked_stock' => 0.000,
                'in_transit_stock' => 0.000,
                'project_stock' => 0.000,
                'wbs_element' => '',
                'valuation_class' => '1000',
                'valuation_description' => 'HAR-Cable',
                'harga_satuan' => 85000,
                'total_harga' => 85000,
                'currency' => 'IDR',
                'pabrikan' => 'SUTRAKABEL INTIMANDIRI',
                'normalisasi' => '',
                'qty' => 1,
                'tanggal_terima' => Carbon::parse('2025-01-13'),
                'keterangan' => 'SELESAI',
                'status' => Material::STATUS_DALAM_PERBAIKAN,
            ],
            // Data tambahan dari format CSV yang diberikan
            [
                'nomor' => 4,
                'company_code' => '5300',
                'company_code_description' => 'UID Jawa Barat',
                'plant' => '5319',
                'plant_description' => 'PLN UP3 Cimahi',
                'storage_location' => '2080',
                'storage_location_description' => 'APJ Cimahi',
                'material_type' => 'ZST1',
                'material_type_description' => 'PLN Stock Materials',
                'material_code' => '000000001060071',
                'material_description' => 'TRF ACC;SERANDANG TRAFO 3P;1 TIANG',
                'material_group' => 'ZM0106',
                'base_unit_of_measure' => 'SET',
                'valuation_type' => 'NORMAL',
                'unrestricted_use_stock' => 10.000,
                'quality_inspection_stock' => 0.000,
                'blocked_stock' => 0.000,
                'in_transit_stock' => 0.000,
                'project_stock' => 0.000,
                'wbs_element' => '',
                'valuation_class' => '1000',
                'valuation_description' => 'HAR-Transformator',
                'harga_satuan' => 4995000,
                'total_harga' => 49950000,
                'currency' => 'IDR',
                'pabrikan' => 'PT TRAFO INDONESIA',
                'normalisasi' => '',
                'qty' => 10,
                'tanggal_terima' => Carbon::parse('2025-01-10'),
                'keterangan' => 'SELESAI',
                'status' => Material::STATUS_BAIK,
            ],
            [
                'nomor' => 5,
                'company_code' => '5300',
                'company_code_description' => 'UID Jawa Barat',
                'plant' => '5319',
                'plant_description' => 'PLN UP3 Cimahi',
                'storage_location' => '2080',
                'storage_location_description' => 'APJ Cimahi',
                'material_type' => 'ZST1',
                'material_type_description' => 'PLN Stock Materials',
                'material_code' => '000000001060072',
                'material_description' => 'TRF ACC;SERANDANG TRAFO 3P;2 TIANG',
                'material_group' => 'ZM0106',
                'base_unit_of_measure' => 'SET',
                'valuation_type' => 'NORMAL',
                'unrestricted_use_stock' => 6.000,
                'quality_inspection_stock' => 0.000,
                'blocked_stock' => 0.000,
                'in_transit_stock' => 0.000,
                'project_stock' => 0.000,
                'wbs_element' => '',
                'valuation_class' => '1000',
                'valuation_description' => 'HAR-Transformator',
                'harga_satuan' => 14430000,
                'total_harga' => 86580000,
                'currency' => 'IDR',
                'pabrikan' => 'PT TRAFO INDONESIA',
                'normalisasi' => '',
                'qty' => 6,
                'tanggal_terima' => Carbon::parse('2025-01-10'),
                'keterangan' => 'PENDING INSTALASI',
                'status' => Material::STATUS_BAIK,
            ],
        ];

        foreach ($materials as $material) {
            Material::create($material);
        }
    }
}